name: PHP CI

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4  # Choose your PHP version

      - name: Install dependencies
        run: cd myphp && composer install


      - name: Run tests
        run: phpunit
        
      # Add more steps as needed (e.g., linting, building assets)

# You can also add deployment steps here
    
